config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", include("reenact.reenact.urls")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

reenact/reenact/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = "reenact"

urlpatterns = [
    path(
        "challenges/",
        TemplateView.as_view(template_name="reenact/challenges.html"),
        name="challenges",
    ),
    path(  # GDPR
        "dsgvo/",
        TemplateView.as_view(template_name="reenact/dsgvo.html"),
        name="dsgvo",
    ),
    path("faq/", TemplateView.as_view(template_name="reenact/faq.html"), name="faq"),
    path(
        "glossary/",
        TemplateView.as_view(template_name="reenact/glossary.html"),
        name="glossary",
    ),
    path(  # legal
        "impressum/",
        TemplateView.as_view(template_name="reenact/impressum.html"),
        name="impressum",
    ),
    path("map/", TemplateView.as_view(template_name="reenact/map.html"), name="map"),
    path(
        "sources/",
        TemplateView.as_view(template_name="reenact/sources.html"),
        name="sources",
    ),
    path("", views.MainView.as_view(), name="index"),
]

reenact/reenact/models.py
# Create your models here.

reenact/reenact/forms.py
from django.forms import Form
from django.forms import IntegerField
from django.forms import NumberInput

from .settings import SliderConfig


class CapacitiesForm(Form):
    template_name_div = "reenact/forms/capacities.html"

    def __init__(self, sliders: list[SliderConfig]):
        super().__init__()
        for slider in sliders:
            self.fields[slider.name] = IntegerField(
                label=slider.label,
                help_text=slider.unit,
                widget=NumberInput(
                    attrs={
                        "class": "js-range-slider",
                        "data-min": slider.min,
                        "data-max": slider.max,
                        "data-step": slider.step,
                        "data-from": slider.initial,
                        "data-skin": "round",
                    },
                ),
            )

reenact/reenact/views.py
from django.views.generic.base import TemplateView

from . import settings
from .forms import CapacitiesForm


class MainView(TemplateView):
    template_name = "reenact/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["capacities"] = CapacitiesForm(sliders=settings.SLIDERS)
        return context

reenact/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}
  Forbidden (403)
{% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

reenact/templates/base.html
{% load static i18n compress %}

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="preload"
          as="image"
          href="{% static 'images/logo-reenact.jpg' %}" />
    <meta name="description" content="Regionale Energiewende aktiv gestalten" />
    <meta name="next-size-adjust" />
    <meta name="author" content="Reiner Lemoine Institut" />
    <title>
      {% block title %}
        ReEnAct
      {% endblock title %}
    </title>
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
    {% block css %}
      <link rel="stylesheet" href="{% static 'css/tailwind.css' %}" />
      <link rel="stylesheet" href="{% static 'css/project.css' %}" />
      <link rel="stylesheet" href="{% static 'css/navigation.css' %}" />
      <link rel="stylesheet"
            href="{% static 'vendors/ionrangeslider/ion.rangeSlider.min.css' %}" />
    {% endblock css %}
    {% block javascript %}
      <script src="{% static 'vendors/jquery/jquery.slim.min.js' %}"></script>
      <script src="{% static 'vendors/ionrangeslider/ion.rangeSlider.min.js' %}"></script>
    {% endblock javascript %}
  </head>
  <body class="{% block bodyclass %}__className_32aa65 text-slate-800 overflow-auto{% endblock bodyclass %}">
    <div class="flex flex-col h-full min-h-screen">
      {% if messages %}
        <div class="container">
          {% for message in messages %}
            <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
              {{ message }}
              <button type="button"
                      class="btn-close"
                      data-bs-dismiss="alert"
                      aria-label="Close"></button>
            </div>
          {% endfor %}
        </div>
      {% endif %}
      {% block navigation %}
        {% include "navigation.html" %}
      {% endblock navigation %}
      {% block content %}
      {% endblock content %}
    </div>
    {% block javascript_inline %}
    {% endblock javascript_inline %}
  </body>
</html>

reenact/templates/cotton/potentials.html
<div class="bg-white p-4">
  <svg
   width="50"
   height="50"
   viewBox="0 0 40.681313 57.535"
   version="1.1"
   xmlns="http://www.w3.org/2000/svg">
    <g id="layer1" transform="translate(-81.518963,-113.70635)">
      <circle
         style="fill:#ffffff;stroke-width:3.535;stop-color:#000000;stroke:{{ color }};stroke-opacity:1;stroke-dashoffset:{{ stroke_dashoffset }};fill-opacity:0"
         id="path13911"
         cx="101.85962"
         cy="142.47385"
         r="27" />
    </g>
  </svg>
  <div class="percentage">{{ percentage }}%</div>
  <h2>{{ title }}</h2>
  <div>{{ value }} {{ unit }}</div>
</div>

reenact/templates/cotton/result_component_box.html
  <div class="bg-white shadow rounded border p-4">
      <h2>{{ title }}</h2>
      <div>
        {{ value1 }} {{unit1}}
        <h3>{{ subtitle1 }}
          <span class="info-icon" data-tooltip="{{ info_hover1 }}">i</span>
        </h3>
      </div>
      <div>
        {{ value2 }} {{unit2}}
      <h3>{{ subtitle2 }}
      <span class="info-icon" data-tooltip="{{ info_hover2 }}">i</span>
      </h3>
      </div>
      <img src="./static/images/scale.svg" alt="scale" width="200" />
  </div>

reenact/templates/navigation.html
{% load static i18n %}

<nav class="bg-white shadow" data-headlessui-state="">
  <div>
    <div class="relative flex items-center justify-between">
      <div class="flex flex-shrink-0">
        <a href="{% url 'reenact:index' %}">
          <img id="hdr-img"
               class="h-8 w-auto"
               src="{% static 'images/logo-reenact.jpg' %}"
               alt="ReEnAct homepage" />
        </a>
      </div>
      <div class="container">
        <h1 class="text-center text-2xl">ENERGIEREGION PEENETAL</h1>
      </div>
      <div class="flex">
        <div class="nav-tab">
          <ul>
            <li>
              <a href="{% url 'reenact:index' %}">Startseite</a>
            </li>
            <li>
              <a href="#">Infos</a>
              <ul>
                <li>
                  <a href="{% url 'reenact:challenges' %}">Chancen und Herausforderungen</a>
                </li>
                <li>
                  <a href="{% url 'reenact:faq' %}">Häufige Fragen</a>
                </li>
                <li>
                  <a href="{% url 'reenact:glossary' %}">Glossar</a>
                </li>
                <li>
                  <a href="{% url 'reenact:sources' %}">Quellen</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="{% url 'reenact:map' %}">Karte</a>
            </li>
            <li>
              <a href="#">Rechtliches</a>
              <ul>
                <li>
                  <a href="{% url 'reenact:impressum' %}">Impressum</a>
                </li>
                <li>
                  <a href="{% url 'reenact:dsgvo' %}">Datenschutzerklärunng</a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

reenact/templates/reenact/challenges.html
{% extends 'base.html' %}

{% block title %}
  Chancen
{% endblock title %}
{% block content %}
  <h1>Chancen und Herausforderungen der Energiewende</h1>
  Die Energiewende bringt Herausforderungen mit sich.
{% endblock content %}

reenact/templates/reenact/dsgvo.html
{% extends 'base.html' %}

{% block title %}
  Datenschutzerklärung
{% endblock title %}
{% block content %}
{% endblock content %}

reenact/templates/reenact/faq.html
{% extends 'base.html' %}

{% block title %}
  FAQ
{% endblock title %}
{% block content %}
  <h1>Häufige Fragen</h1>
  <details>
    <summary>1. Was sind die Energieziele der EU?</summary>
    Gerne mit Inhalt füllen.
  </details>
  <details>
    <summary>2. Was bedeuten die EU-Energieziele für die Region Peenetal?</summary>
    Gerne mit Inhalt füllen.
  </details>
{% endblock content %}

reenact/templates/reenact/forms/capacities.html
{% for field in form %}
  <div>
    {{ field.label }} {{ field.help_text }}
    {{ field }}
  </div>
{% endfor %}

reenact/templates/reenact/glossary.html
{% extends 'base.html' %}

{% block title %}
  Glossar
{% endblock title %}
{% block content %}
  <h1>Glossar</h1>
  <h2>Autarkie</h2>
  Selbstversorgung, bei der eine Region oder ein Haushalt den gesamten Energiebedarf unabhängig deckt.
  <hr />
  <h2>Bilanzziel</h2>
{% endblock content %}

reenact/templates/reenact/impressum.html
{% extends 'base.html' %}

{% block title %}
  Impressum
{% endblock title %}
{% block content %}
{% endblock content %}

reenact/templates/reenact/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  ReEnAct
{% endblock title %}
{% block content %}
  <div class="grid grid-cols-1 gap-4">
    <section>
      <div>
        <nav class="py-4 text-center">
          <ul class="flex justify-center space-x-4">
            <li>
              <a href="#">2024</a>
            </li>
            <li>
              <a href="#">Szenarien 2040</a>
            </li>
            <li>
              <a href="#">Mein Plan 2040</a>
            </li>
            <li>
              <a href="#">Szenarienvergleich</a>
            </li>
          </ul>
        </nav>
      </div>
      <div class="grid grid-cols-2 gap-4">
        <div class="p-4">
          <p>Content mid left</p>
        </div>
        <div class="p-4">
          <p>Content mid right</p>
          <form>
            {{ capacities.as_div }}
          </form>
        </div>
      </div>
    </section>
    <section class="grid grid-cols-2 gap-4">
      <div class="p-4">
        <p>Content bottom left</p>
      </div>
      <div class="p-4">
        <p>Content bottom right</p>
      </div>
    </section>
  </div>
{% endblock content %}
{% block javascript_inline %}
  <script src="{% static 'js/sliders.js' %}"></script>
{% endblock javascript_inline %}

reenact/templates/reenact/map.html
{% extends 'base.html' %}

{% load static i18n compress %}

{% block title %}
  Karte
{% endblock title %}
{% block css %}
  {{ block.super }}
  <link rel="stylesheet"
        href="https://unpkg.com/leaflet@latest/dist/leaflet.css" />
  <link rel="stylesheet" href="{% static 'css/map.css' %}" />
{% endblock css %}
{% block javascript %}
  <script src="https://unpkg.com/leaflet@latest/dist/leaflet.js"></script>
{% endblock javascript %}
{% block content %}
  <div id="mapframe"></div>
  <script>
    var map = L.map('mapframe').setView([54, 13.8], 10);
    // various links
    const osmLink = '<a href="https://openstreetmap.org">OpenStreetMap</a>';

    // base layers
    L.tileLayer(
      'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: 'Tiles &copy; ' + osmLink + ' Contributors',
        maxZoom: 19,
      }).addTo(map);

    //const gisLink = 'Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community';
    //L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
    //attribution: 'Tiles &copy; ' + gisLink,
    //maxZoom: 19,
    //}).addTo(map);
  </script>
{% endblock content %}

reenact/templates/reenact/sources.html
{% extends 'base.html' %}

{% block title %}
  Quellen
{% endblock title %}
{% block content %}
{% endblock content %}